title:
  roberta:
    path: ''
  xlm-roberta:
    path: 'D:\dcmt\model\hf\FacebookAI\xlm-roberta-base'
  clip:
    path: ''


text:
  blip:
    path: ''
  roberta:
    path: ''
  xlm-roberta:
    path: 'D:\dcmt\model\hf\FacebookAI\xlm-roberta-base'
  clip:
    path: ''


image:
  vit:
    path: ''


audio:
  wav2vec2:
    path: ''


