title:
  roberta:
    path: ''
  xlm-roberta:
    path: 'D:\dcmt\model\hf\FacebookAI\xlm-roberta-base'
  clip:
    path: 'D:\dcmt\model\hf\openai\clip-vit-base-patch32'


text:
  blip:
    path: ''
  roberta:
    path: ''
  xlm-roberta:
    path: 'D:\dcmt\model\hf\FacebookAI\xlm-roberta-base'
  clip:
    path: 'D:\dcmt\model\hf\openai\clip-vit-base-patch32'


image:
  vit:
    path: ''


audio:
  wav2vec2:
    path: 'D:\dcmt\model\hf\facebook\wav2vec2-base-960h'


